name: FRONTEND-CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'vega-be/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'vega-be/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: vega-be
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn type-check